
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack-pro  # complete emulator
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/

      # Auth Token
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}  # required for Pro

      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=1 # persist data to volume
      - SERVICES=s3,ec2,elb,autoscaling,cloudwatch,rds,apigateway,cognito-idp,iam,route53,sts,sns,cognito,sesv2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - DISABLE_CORS_CHECKS=1
      - HOSTNAME_EXTERNAL=localhost.localstack.cloud
      - EC2_DOCKER_FLAGS=-p 80:80
      - LAMBDA_DOCKER_NETWORK=docker_default
      - MAIN_DOCKER_NETWORK=docker_default
    networks:
      - default
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  