
services:
  # --- LOCALSTACK ---
  localstack:
    container_name: localstack_main
    image: localstack/localstack-pro  # complete emulator
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/

      # Auth Token
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}  # required for Pro

      # Extensions for Terraform INIT HOOK
      - EXTENSION_AUTO_INSTALL=localstack-extension-terraform-init

      - DEBUG=${DEBUG:-0}
      # - PERSISTENCE=1 # persist data to volume
      # - SERVICES=s3,ec2,elb,autoscaling,cloudwatch,rds,apigateway,cognito-idp,iam,route53,sts,sns,cognito,sesv2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - DISABLE_CORS_CHECKS=1
      - LAMBDA_DOCKER_NETWORK=docker_default
      - MAIN_DOCKER_NETWORK=docker_default

      # NO. QUESTO FLAG MAPPA LA PORTA 80 DEL CONTAINER EC2 ALLA PORTA 80 HOST
      # MA LO FA PER OGNI CONTAINER CON EC2 CHE VIENE CREATO, QUINDI
      # AL PRIMO CONTAINER VA BENE, AL SECONDO DA ERRORE PERCHÈ LA PORTA 80 HOST
      # È GIÀ IN USO. SENZA QUESTO FLAG RIUCIAMO A CREARE PIÙ ISTANZE EC2 SENZA PROBLEMI.
      # - EC2_DOCKER_FLAGS=-p 80:80
    networks:
      - default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
        # - "./volume:/var/lib/localstack"
      - localstack_data:/var/lib/localstack
      # LOCALSTACK INIT HOOKS con terraform
      - ./terraform:/etc/localstack/init/ready.d
      - localstack_env:/config


  # --- BACKEND ---
  backend:
    container_name: backend_fastapi
    build: ./backend
    volumes:
      - ./backend:/app
      # - ./terraform:/app/terraform  # montiamo il folder che conterrà .env_localstack
      # - ./terraform:/config
      - localstack_env:/config
    ports:
      - "8000:8000"
    env_file: # carica variabili d'ambiente da file, ne possiamo specificare più di uno
    - path: ./backend/.env
      required: true
    
    # inutile perchè appena parte il container questo file non esiste ancora, viene creato dopo da terraform init hook
    # - path: ./terraform/localstack.env
    #   required: false
    depends_on:
      - localstack
    networks:
      - default



  # --- FRONTEND ---
  frontend:
    container_name: frontend_sveltekit
    build: ./frontend
    volumes:
      # Hot Reload (codice locale -> container)
      - ./frontend:/app # bind mount del codice sorgente
      - /app/node_modules # volume anonimo per node_modules, non considera /node_modules locale ma solo quello del container
      # - ./terraform:/app/terraform  # monta .env_localstack. no perchè /app è gia montato in ./frontend, poi creerebbe una cartella terraoform lì
      # - ./terraform:/config
      - localstack_env:/config
    ports:
      - "5173:5173"
    env_file:
      - path: ./frontend/.env
        required: true

      # inutile perchè appena parte il container questo file non esiste ancora, viene creato dopo da terraform init hook
      # - path: ./terraform/localstack.env
      #   required: false
    depends_on:
      - localstack
    networks:
      - default


volumes:
  localstack_data:
  localstack_env:

networks:
  default:
    driver: bridge